name: "ITP"

services:

  mariadb:
    image: mariadb:11.4
    container_name: mariadb-itp-projekt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ITP_DBMS_NAME}
      MYSQL_DATABASE: ${ITP_DATABASE_NAME}
      MYSQL_USER: ${ITP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${ITP_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - itp_mariadb_network

  frontend:
    build:
      context: ../home-management
      dockerfile: Dockerfile
    container_name: itp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - itp_mariadb_network

# ── Volumes und Networks auf oberster Ebene (NICHT unter services!) ────────
volumes:
  mariadb_data:

networks:
  itp_mariadb_network:
    driver: bridge