name: "ITP"
version: "3.9"
services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb-itp-projekt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ITP_DBMS_NAME}
      MYSQL_DATABASE: ${ITP_DATABASE_NAME}
      MYSQL_USER: ${ITP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${ITP_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge
